---
- name: Target Workstation defaults
  hosts: '{{ target }}'
  gather_facts: False
  remote_user: push
  become: true
  tasks:

# Remove Game from Target Desktop

    - name: Remove Game package
      apt: name=gnome-games-common state=absent

    - name: Remove Game package gnome-sudoku
      apt: name=gnome-sudoku state=absent

    - name: Remove Game package gnome-mines 
      apt: name=gnome-mines state=absent
